// item
export const SIMPLE_ORDER_SUBMIT = 'SIMPLE_ORDER_SUBMIT'
export const ITEM_WEIGHT = 'ITEM_WEIGHT'
export const ITEM_DESCRIPTION = 'ITEM_DESCRIPTION'
export const ITEM_FRAGILE = 'ITEM_FRAGILE'
export const ITEM_RESET = 'ITEM_RESET'

// sender
export const PICKUP_LOCATION_SELECTED = 'PICKUP_LOCATION_SELECTED'
export const PICKUP_LOCATION_LINE_TWO_FILLED = 'PICKUP_LOCATION_LINE_TWO_FILLED'
export const PICKUP_ZIPCODE_FILLED = 'PICKUP_ZIPCODE_FILLED'
export const SENDER_FIRST_NAME_FILLED = 'SENDER_FIRST_NAME_FILLED'
export const SENDER_LAST_NAME_FILLED = 'SENDER_LAST_NAME_FILLED'
export const SENDER_PHONE_FILLED = 'SENDER_PHONE_FILLED'
export const SENDER_EMAIL_FILLED = 'SENDER_EMAIL_FILLED'
export const SENDER_RESET = 'SENDER_RESET'

// receiver 
export const DROPOFF_LOCATION_SELECTED = 'DROPOFF_LOCATION_SELECTED'
export const DROPOFF_LOCATION_LINE_TWO_FILLED = 'DROPOFF_LOCATION_LINE_TWO_FILLED'
export const DROPOFF_ZIPCODE_FILLED = 'DROPOFF_ZIPCODE_FILLED'
export const RECEIVER_FIRST_NAME_FILLED = 'RECEIVER_FIRST_NAME_FILLED'
export const RECEIVER_LAST_NAME_FILLED = 'RECEIVER_LAST_NAME_FILLED'
export const RECEIVER_PHONE_FILLED = 'RECEIVER_PHONE_FILLED'
export const RECEIVER_EMAIL_FILLED = 'RECEIVER_EMAIL_FILLED'
export const RECEIVER_RESET = 'RECEIVER_RESET'

// order 
export const QUOTE_RETURN = 'QUOTE_RETURN'
export const ORDER_NUMBER_RETURN = 'ORDER_NUMBER_RETURN'
export const SHIP_METHOD_SELECTED = 'SHIP_METHOD_SELECTED'
export const ORDER_PRICE_UPDATED = 'SET_ORDER_PRICE'
export const ORDER_EST_DATE_UPDATED = 'SET_ORDER_EST_DATE'
export const ORDER_EST_TIME_UPDATED = 'SET_ORDER_EST_TIME'
export const ORDER_RESET = 'ORDER_RESET'

// page 
export const PAGE_INCREMENT = 'PAGE_INCREMENT'
export const PAGE_DECREMENT = 'PAGE_DECREMENT'
// export const PAGE_INCREMENT_FROM_ONE_TO_TWO = 'PAGE_INCREMENT_FROM_ONE_TO_TWO'
// export const PAGE_INCREMENT_FROM_TWO_TO_THREE = 'PAGE_INCREMENT_FROM_TWO_TO_THREE'
export const PAGE_ON_ENTER = 'PAGE_ON_ENTER'
export const PAGE_ON_EXITED = 'PAGE_ON_EXITED'
export const COLLAPSE_INCREMENT = 'COLLAPSE_INCREMENT'
export const COLLAPSE_DECREMENT = 'COLLAPSE_DECREMENT'
export const PAGE_RESET = 'PAGE_RESET'

// user 
export const ACCOUNT_SUMMARY_RETURN = 'ACCOUNT_SUMMARY_RETURN'
export const SHOW_DATA = 'SHOW_DATA'
export const TOKEN_RETURN = 'TOKEN_RETURN'
export const ORDER_HISTORY_RETURN = 'ORDER_HISTORY_RETURN'
export const LOGOUT = 'LOGOUT'